#!/bin/sh -e

. /usr/share/debconf/confmodule

CONFIGFILE="/etc/matrix-synapse/conf.d/server_name.yaml"
USER="matrix-synapse"

case "$1" in
  configure|reconfigure)
    # Set server name in config file
    mkdir -p "/etc/matrix-synapse/conf.d/"
    db_get matrix-synapse/server-name
    echo "server_name: $RET" > $CONFIGFILE

    if ! getent passwd $USER >/dev/null; then
      adduser --quiet --system --no-create-home --home /var/lib/matrix-synapse $USER
    fi

    for DIR in /var/lib/matrix-synapse /var/log/matrix-synapse; do
      if ! dpkg-statoverride --list --quiet $DIR >/dev/null; then
        dpkg-statoverride --force --quiet --update --add $USER nogroup 0755 $DIR
      fi
    done

    ;;
esac

#DEBHELPER#

exit 0
