Document: synapse
Title: Debian synapse Manual
Author: <insert document author here>
Abstract: This manual describes what synapse is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/synapse/synapse.sgml.gz

Format: postscript
Files: /usr/share/doc/synapse/synapse.ps.gz

Format: text
Files: /usr/share/doc/synapse/synapse.text.gz

Format: HTML
Index: /usr/share/doc/synapse/html/index.html
Files: /usr/share/doc/synapse/html/*.html
